apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  selector:
    app: httpbin
  type: ClusterIP
  ports:
  - name: httpbin
    port: 8000
    targetPort: httpbin
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deployment
spec:
  replicas: 1
  template:
    metadata:
    labels:
      app: httpbin
    spec:
      containers:
        - name: httpbin
          image: citizenstig/httpbin
          ports:
          - name: httpbin
            containerPort: 8000
            protocol: TCP
