---
# Deploying your public key to the remote hosts 
# https://medium.com/@visualskyrim/ansible-playbook-deploy-the-public-key-to-remote-hosts-da3f3b4b5481      
# Use with:  ansible-playbook -i <inventory-file> deploy_authorized_keys.yml --ask-pass --extra-vars='pubkey="<pubkey>"'

- hosts: all
  tasks:
  - name: make direcotry
    file:
      path: "/home/<username>/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/<username>/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/<username>/.ssh/authorized_keys"
      line: "{{ pubkey }}"