aws_region = "us-west-2"
application_name = "charliedelta"
environment_name = "staging"
vpc_cidr = "10.50.0.0/16"
public_key_path = "../credentials/main-ec2-key.pub"
#admin_email = "sjncd2000@gmail.com"